[=== Module cuda/10.0 loaded ===]
[=== Module cuda/10.0/cudnn/7.6 loaded ===]
2020-05-01 19:21:56.696883: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:76] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.
2020-05-01 19:21:56.697088: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:77] Searched for CUDA in the following directories:
2020-05-01 19:21:56.697100: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:80]   ./cuda_sdk_lib
2020-05-01 19:21:56.697105: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:80]   /usr/local/cuda
2020-05-01 19:21:56.697109: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:80]   .
2020-05-01 19:21:56.697114: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:82] You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.
2020-05-01 19:21:57.936514: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/llvm_gpu_backend/gpu_backend_lib.cc:305] libdevice is required by this HLO module but was not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "hyper_tune.py", line 264, in <module>
    app.run(main)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "hyper_tune.py", line 39, in main
    run_for_agent(FLAGS.agent, lr_vanilla)
  File "hyper_tune.py", line 123, in run_for_agent
    total_rmsve, final_rmsve, start_rmsve, avg_steps = run_objective(space)
  File "hyper_tune.py", line 252, in run_objective
    env, agent, mdp_solver = run_experiment(seed, space, aux_agent_configs)
  File "/network/home/cheluver/jax_models/main_utils.py", line 290, in run_experiment
    agent = get_agent(env, seed, nrng, nA, input_dim, policy, space, aux_agent_configs)
  File "/network/home/cheluver/jax_models/main_utils.py", line 250, in get_agent
    target_networks=space["agent_config"]["target_networks"])
  File "/network/home/cheluver/jax_models/network.py", line 37, in get_network
    rng, input_dim)
  File "/network/home/cheluver/jax_models/network.py", line 156, in get_extrinsic_network
    v_network, v_network_params = get_value_net(rng_v, input_size, bias=False)
  File "/network/home/cheluver/jax_models/network_utils/value_net_utils.py", line 17, in get_value_net
    _, v_network_params = v_network_init(rng_v, (-1, num_units))
  File "/network/home/cheluver/jax_models/custom_layers.py", line 21, in init_fun
    W = W_init(rng, (input_shape[-1], out_dim))
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/jax/nn/initializers.py", line 61, in init
    stddev = np.sqrt(variance) / np.array(.87962566103423978, dtype)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/jax/numpy/lax_numpy.py", line 389, in fn
    return lax_fn(x)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/jax/lax/lax.py", line 250, in sqrt
    return sqrt_p.bind(x)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/jax/core.py", line 179, in bind
    return self.impl(*args, **kwargs)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/jax/interpreters/xla.py", line 158, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *map(arg_spec, args), **params)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/jax/interpreters/xla.py", line 183, in xla_primitive_callable
    compiled = built_c.Compile(compile_options=options, backend=backend)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/jaxlib/xla_client.py", line 586, in Compile
    return backend.compile(self.computation, compile_options)
  File "/network/home/cheluver/miniconda3/envs/new/lib/python3.6/site-packages/jaxlib/xla_client.py", line 158, in compile
    compile_options.device_assignment)
RuntimeError: Internal: libdevice not found at ./libdevice.10.bc
